language: java
jdk:
  - openjdk8

branches:
  only:
    - main

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

before_install:
  - chmod +x gradlew

script: "./gradlew clean build -x test"

before_deploy:
  - zip -r springboot-web-practise *
  - mkdir -p deploy
  - mv springboot-web-practise.zip deploy/springboot-web-practise.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: springboot-webservice-buket
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    local_dir: deploy
    wait-until-deployed: true
    on:
      repo: selre1/study
      branch: main

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - selre1@naver.com
